Alright so I finally recreated the steps necessary to connect Moralis' server to my smart contract:

```
eth_chainId
  Contract deployment: MintOneToken
  Contract address:    0x5fbdb2315678afecb367f032d93f642f64180aa3
  Transaction:         0x5a488dd6224a6d1dc958988bc25db69ecf22a6ac12b8eec3781886beb9ccfdf5
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  Value:               0 ETH
  Gas used:            2064235 of 2064235
  Block #1:            0x9fbf0f3baafeaf61f54f5db22c47f0b2678a87913e3570b2bde5ceec1608f2d1
  Contract deployment: MarsKetplace
  Contract address:    0xe7f1725e7734ce288f8367e1bb143e90bb3f0512
  Transaction:         0xa5c28ae267cb0960ee4afe3ade9658d8ccfc089ca838d1466f7029448298b401
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  Value:               0 ETH
  Gas used:            1335062 of 1335062
  Block #2:            0xea709275b5ac49fa888ec259fc89ba9fedfcef286808b33e7aa362c5e925c027

eth_blockNumber
eth_chainId (4)
eth_blockNumber (2)
eth_chainId
eth_getBlockByNumber
eth_chainId
eth_getBlockByNumber
eth_getTransactionReceipt (2)
eth_blockNumber
eth_chainId
eth_getBlockByNumber
eth_getTransactionReceipt
eth_blockNumber (339)
```

The last line shows that Moralis is constantly checking the `eth_blockNumber`, which means Moralis connected to my local testnet

- need to encode in `.env` the moralis' cli api key and secret, so I don't have to enter them every time I deploy
- need to run again the command to register event listeners

the script `addEventsMoralis.js` is still failing.
used `console.log` to debug the `responses` :
`{ success: false, error: 'tableName should only contain letters' }`

I changed the name of those tableName, and now:
`{ success: false }`

I've looked online for similar problems and checked the resolution of each problem, but nothing works so far.
I'll delete the server and create a new one, replace the variables in .env once it's done and try again

I've tried changing the .env variables by adding or removing quotation marks
the server is still correctly connected but something prevents the boolean `success` from returning `true`, that's what the log journal tells me:

```
2022-09-07T12:25:03.121Z - Ran cloud function watchContractEvent for user undefined with:
  Input: {"chainId":"31337","address":"0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512","sync_historical":true,"topic":"NFTDeleted(address,uint256)","abi":{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"nftAddress","type":"address"},{"indexed":true,"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"NFTDeleted","type":"event"},"tableName":"NFTDeleted"}
  Result: {"success":false}
```

There are no error logs on the Logs/error folder
